<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moduleeer" nsURI="http://moduleeer/1.0" nsPrefix="moduleeer">
  <eClassifiers xsi:type="ecore:EClass" name="MEERModel" eSuperTypes="#//NameElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextDataModels" upperBound="-1"
        eType="#//ContextDataModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystems" upperBound="-1"
        eType="#//subsystem/ModuleSubsystem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="#//ModularizableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessElement" upperBound="-1"
        eType="#//procedure/AccessElement" eOpposite="#//procedure/AccessElement/entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//ContextDataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//procedure/Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modularizableElements"
        upperBound="-1" eType="#//ModularizableElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityType" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalizes" upperBound="-1"
        eType="#//EntityType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcRelationshiptype" upperBound="-1"
        eType="#//RelationshipType" eOpposite="#//RelationshipType/srcEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trgRelationshiptype" upperBound="-1"
        eType="#//RelationshipType" eOpposite="#//RelationshipType/trgEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipType" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcEntity" eType="#//EntityType"
        eOpposite="#//EntityType/srcRelationshiptype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trgEntity" eType="#//EntityType"
        eOpposite="#//EntityType/trgRelationshiptype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcEntityCardinality" eType="#//CardinalityType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trgEntityCardinality" eType="#//CardinalityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AttributeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeType">
    <eLiterals name="STRING"/>
    <eLiterals name="NUMERIC" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="DATE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CardinalityType">
    <eLiterals name="ZERO"/>
    <eLiterals name="ONE" value="1"/>
    <eLiterals name="MANY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModularizableElement" abstract="true"
      eSuperTypes="#//NameElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextDataModel" abstract="true" eSuperTypes="#//NameElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubjectArea" eSuperTypes="#//ContextDataModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextDataModels" upperBound="-1"
        eType="#//ContextDataModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//NameElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eSubpackages name="subsystem" nsURI="http://moduleeer/subsystem/1.0" nsPrefix="subsystem">
    <eClassifiers xsi:type="ecore:EClass" name="ModuleSubsystem" eSuperTypes="#//NameElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" upperBound="-1"
          eType="#//procedure/Procedure"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="procedure" nsURI="http://moduleeer/procedure/1.0" nsPrefix="procedure">
    <eClassifiers xsi:type="ecore:EClass" name="Procedure" eSuperTypes="#//ModularizableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="procedureType" eType="#//procedure/ProcedureType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//procedure/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accessElements" upperBound="-1"
          eType="#//procedure/AccessElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ProcedureType">
      <eLiterals name="PRIVATE"/>
      <eLiterals name="PUBLIC" value="1"/>
      <eLiterals name="REFERENCIAL_INTEGRITY" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//NameElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="integrityProcedures"
          upperBound="-1" eType="#//procedure/Procedure"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AccessElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
          eType="#//Element" eOpposite="#//Element/accessElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessType" eType="#//procedure/OperationType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OperationType">
      <eLiterals name="Read"/>
      <eLiterals name="Read_Write" value="1"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
